- name: Status a Compute
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    ocid: "ocid1.instance.oc1.iad.anuwcljtj6x6wyqcgop7zcqseywyso4xkksl3o5jerlmatnesheemaam6rbq"
  tasks:
  - name: Perform action status of instance
    oci_compute_instance:
      instance_id: "{{ ocid }}"
    register: st
  - debug:
      var=st.instance.lifecycle_state
  - debug:
      var=st.instance.primary_private_ip
  - debug:
      var=st
