- hosts: localhost
  ansible_connection: local
  collections:
    - oracle.oci
  vars:
    ocid: "ocid1.instance.oc1.iad.anuwcljtj6x6wyqcgop7zcqseywyso4xkksl3o5jerlmatnesheemaam6rbq"
  tasks:
  - oci_compute_instance:
      instance_id: "{{ ocid }}"
    register: st
  - debug:
      var=st.instance.lifecycle_state
